### 데이터셋 생성

In [1]:
import numpy as np
import pandas as pd

student = ['야스오', '오공', '블리츠', '페이커']

math_study_time = [2, 4, 6, 8]
eng_study_time = [3, 8, 2, 4]
sci_study_time = [1, 9, 7, 6]
score = [3, 7, 5, 8]

dataset = pd.DataFrame({'math':math_study_time, 'english':eng_study_time, 'science':sci_study_time, 'score':score}, index=student)
dataset.head()

math  english  science  score
야스오     2        3        1      3
오공      4        8        9      7
블리츠     6        2        7      5
페이커     8        4        6      8

In [2]:
y_train = dataset['score'].to_numpy()
X_train = dataset.drop('score', axis=1).to_numpy()
print(X_train, y_train)

[[2 3 1]
 [4 8 9]
 [6 2 7]
 [8 4 6]] [3 7 5 8]


### 가설함수 설정
w1x1 + w2x2 + w3x3 + b

In [3]:
W = np.ones((3, 1))
print(W)

[[1.]
 [1.]
 [1.]]


In [4]:
from random import *

# b = np.random.rand(1, 1)
b = np.ones((1, 1))
print(b)

[[1.]]


In [5]:
def f(X):
    return np.dot(X, W) + b

In [6]:
y_pred = f(X_train)
print(y_pred)

[[ 7.]
 [22.]
 [16.]
 [19.]]


### Cost Function

In [7]:
def loss_function(y, y_pred):
    n_samples = len(y_pred)
    deviation = y_pred - y
    cost = np.sum(np.square(deviation)) / n_samples
    return cost

In [8]:
loss_function(y_train, y_pred)

561.0

### Weight, Bias Update

In [9]:
def gradient(X_train, y_train, y_pred):
    n_samples = len(y_train)
    dw = (1/n_samples) * np.dot(X_train.T, (y_pred - y_train))
    return dw

In [10]:
dw = gradient(X_train, y_train, y_pred)

In [11]:
def gradient_descent(W, learning_rate, dw):
     W = W - learning_rate * dw
     return W

In [12]:
W = gradient_descent(W, 0.01, dw)
print(W)

[[0.275  0.475  0.375  0.525 ]
 [0.365  0.535  0.45   0.5775]
 [0.095  0.325  0.21   0.3825]]


In [13]:
losses = []

for i in range(100):
    y_pred = f(X_train)

    loss = loss_function(y_train, y_pred)
    losses.append(loss)

    dw = gradient(X_train, y_train, y_pred)
    W = gradient_descent(W, 0.01, dw)

    print('W: {}, loss: {}'.format(W, loss))

W: [[ 0.187275   0.418825   0.30305    0.4767125]
 [ 0.281925   0.476425   0.379175   0.52505  ]
 [-0.020775   0.231175   0.1052     0.2941625]], loss: 20.443715624999996
W: [[ 0.17994588  0.42153438  0.30074013  0.4819315 ]
 [ 0.268855    0.46949012  0.36917256  0.51964891]
 [-0.03667325  0.21104538  0.08718606  0.27297503]], loss: 11.660672773242187
W: [[ 0.18258228  0.43129407  0.30693817  0.49347201]
 [ 0.2648175   0.46929881  0.36705815  0.52041913]
 [-0.03989639  0.20041197  0.08025779  0.26048906]], loss: 11.39548329160018
W: [[ 0.18628685  0.44156776  0.31392731  0.50538799]
 [ 0.26208879  0.47015517  0.36612198  0.52217176]
 [-0.04147692  0.19114896  0.07483602  0.24930543]], loss: 11.274642458584138
W: [[ 0.18994521  0.45154796  0.32074658  0.51694864]
 [ 0.25968157  0.47132312  0.36550235  0.52423351]
 [-0.04281218  0.18222375  0.06970578  0.23848273]], loss: 11.163451296690702
W: [[ 0.19342682  0.46115073  0.32728877  0.52808171]
 [ 0.25746128  0.47269495  0.36507812  0.526