# Multi-Variable Linear Regression Example with Pytorch Models (다중 변수의 선형회귀)
- 국립한밭대학교 컴퓨터공학과 임경태
- https://sites.google.com/view/aailab

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x_train = np.array([[2, 3, 1], 
                    [4, 8, 9], 
                    [6, 2, 7], 
                    [8, 4, 6]])
y_train = np.array([[3], 
                    [7], 
                    [5], 
                    [8]])

n_samples = x_train.shape[0]
n_features = x_train.shape[1]
losses = []

In [3]:
import torch

torch.nn.Linear \_\_init\_\_()

```
    def __init__(self, in1_features: int, in2_features: int, out_features: int, bias: bool = True,
                 device=None, dtype=None) -> None:
        factory_kwargs = {'device': device, 'dtype': dtype}
        super(Bilinear, self).__init__()
        self.in1_features = in1_features
        self.in2_features = in2_features
        self.out_features = out_features
        self.weight = Parameter(torch.empty((out_features, in1_features, in2_features), **factory_kwargs))

        if bias:
            self.bias = Parameter(torch.empty(out_features, **factory_kwargs))
        else:
            self.register_parameter('bias', None)
        self.reset_parameters()
```



In [4]:
linear_model = torch.nn.Linear(in_features=3, out_features=1)

print(linear_model)
print(list(linear_model.parameters()))

Linear(in_features=3, out_features=1, bias=True)
[Parameter containing:
tensor([[0.5546, 0.4457, 0.2460]], requires_grad=True), Parameter containing:
tensor([0.1530], requires_grad=True)]


In [5]:
x_train_torch = torch.from_numpy(x_train).float()
y_train_torch = torch.from_numpy(y_train).float()
print(x_train_torch)
print(x_train_torch.shape)

tensor([[2., 3., 1.],
        [4., 8., 9.],
        [6., 2., 7.],
        [8., 4., 6.]])
torch.Size([4, 3])


In [6]:
predicted_y = linear_model(x_train_torch)  # forward 함수 실행

torch.nn.Linear forward()
```
    def forward(self, input: Tensor) -> Tensor:
        return F.linear(input, self.weight, self.bias)
```



In [7]:
optimizer = torch.optim.SGD(linear_model.parameters(), lr=0.01)  # 업데이트할 파라미터를 지정(linear_model.parameters())
loss_function = torch.nn.MSELoss()

In [8]:
linear_model.train()
for idx in range(100):
  optimizer.zero_grad()
  predicted_y = linear_model(x_train_torch)
  loss = loss_function(predicted_y, y_train_torch)  
  print(loss.item())
  loss.backward()
  optimizer.step()

0.6425564289093018
0.47648561000823975
0.37229034304618835
0.30499011278152466
0.2598814368247986
0.22828640043735504
0.20506255328655243
0.18714553117752075
0.17269760370254517
0.16060250997543335
0.15017428994178772
0.14098221063613892
0.1327490210533142
0.12529124319553375
0.11848177015781403
0.11222980916500092
0.10646726191043854
0.10114097595214844
0.09620796144008636
0.09163199365139008
0.08738227933645248
0.08343236893415451
0.07975813746452332
0.07633823156356812
0.07315360754728317
0.0701865702867508
0.06742135435342789
0.06484293937683105
0.06243814900517464
0.06019458919763565
0.05810059607028961
0.05614569038152695
0.05432021990418434
0.05261501669883728
0.05102146416902542
0.04953200742602348
0.048139262944459915
0.04683660715818405
0.045617781579494476
0.04447680711746216
0.04340840131044388
0.04240765422582626
0.0414697527885437
0.040590282529592514
0.03976532071828842
0.038991160690784454
0.038264110684394836
0.037581223994493484
0.036939170211553574
0.0363354012370109